### ISSUE TITLE
File upload error handling

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#114]
As a user, I want to be notified politely if and why my file does not upload, so that I can fix the issue and try again.

## Definition of Done
- [ ] Upload file button rejects corrupted files and alerts user
- [ ] Upload file rejects (for now) any files that are not .csv and alerts user

Note: Allowed file types may need to change depending on new parsing and data handling methods

## Tasks
- [ ] Upload button checks for corrupted files
- [ ] Upload button checks for .csv file type
- [ ] Error message is displayed to user if file is corrupted
- [ ] Error message is displayed to user if file is not .csv

**Comment by shuai-yang** [comment]
Error message is displayed to user if file is not .csv
![image](https://user-images.githubusercontent.com/5439644/197669070-a22135ab-65e6-4a2f-a202-d492a0c596c0.png)
 Error message is displayed to user if file is corrupted (meaning not fully uploaded e.g. cancelled)
![image](https://user-images.githubusercontent.com/5439644/197669031-59dd065d-63d0-44b5-958a-f13c5ea909d3.png)

**Comment by shuai-yang** [comment]
Note: spent 0.5 hours on research before starting coding and spent 1 hour coding and communicating with team about this story.
