### ISSUE TITLE
Improve Geometry parser and ensure coordination with Results parser

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#151]
As a developer, I want to ensure my app takes in and parses data securely and properly, so that I can use the data and know it is safe and accurate.

## Definition of Done
- [x] Parser takes into account file types
- [x] No extra spaces or empty arrays included in parsed data
- [x] Parser reflects new understanding of element data organization
- [x] Parser works well alongside and does not interfere with .csv parsing solution

## Tasks
- [x] #173
- [x] #174
- [x] #175
- [x] #176
- [x] #178
- [x] #197
- [x] #177

**Comment by katerosenthal** [comment]
In total, this story took around 2.6 hours:

- 40 minutes on file-type checking
- 20 minutes on trimming additional spaces from parsed data
- 40 minutes on removing extra/empty arrays 
- 15 minutes on storing starting node number and total number of nodes
- 10 minutes on updating our element session data storage and naming conventions
- 30 minutes on testing
