### ISSUE TITLE
Integrate Results file parsing with uploading a file 

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#152]
As a developer, I want to be able to parse a Results file that is uploaded by a user, so that I can work with user-provided Results data.

## Definition of Done
- [x] Results files can be safely uploaded to the application
- [x] Results files are stored as session data or their final parsed data is
- [x] Integrated Results parser works well alongside and does not interfere with .inp parsing solution

## Tasks
- [x] #169 
- [x] #172

**Comment by mitchcrocker** [comment]
parsing function will need to be changed regarding how the parameters are used. Possibly add a file path variable depending on where the csv files are being stored. The parsing function will also need to be called in the main html file I assume.
