### ISSUE TITLE
Update 'Upload' button into functional 'Draw' button

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#154]
As a user, I want to be able to click a button to draw my knee visualization, so that I can have more control over when images will appear or update.

## Definition of Done
- [ ] Upload button says 'Draw'
- [ ] Canvas is blank until 'Draw' button is pushed
- [ ] When 'Draw' button is pushed, an image is drawn on the canvas

## Tasks
- [ ] Task 1
- [ ] Task 2

**Comment by mariotorres1** [comment]
Overall this story took about 2 hours of task work/discussion. Each task has a better breakdown of how long each took except #185. This was a discussion amongst the group in discord so it was hard to really say how long that task took.
