### ISSUE TITLE
Update fonts and text in app to be custom and responsive

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#156]
As a user, I want to see more attractive and unique fonts on a page, so that I can feel the page took more effort and is more professional.

## Definition of Done
- [x] New fonts added to project and applied
- [x] At minimum, title and subtitle fonts are responsive to changing window size
- [x] Project title and subtitle updated with new product name
- [x] Font sizes and choices make sense and look attractive to users

## Tasks
- [x] Add new fonts
- [x] Make titles look attractive

**Comment by shuai-yang** [comment]
Blue (Pantone 286 C) and Orange (Pantone 172 C)

**Comment by shuai-yang** [comment]
full size: 


![Image](https://user-images.githubusercontent.com/5439644/200680451-c614387f-2384-4632-96b6-0681a6d4ae29.png)


changed window size:





![Image](https://user-images.githubusercontent.com/5439644/200680754-478acf84-248e-4518-9224-3a7e4ae8c4f0.png)

**Comment by shuai-yang** [comment]
To Do: Fix issues in style.css for the linter. 

![image](https://user-images.githubusercontent.com/5439644/200786110-bdb910a5-fa1a-4850-b3cf-e20c8c97c876.png)

**Comment by shuai-yang** [comment]
Fixed on Nov 11th.
![image](https://user-images.githubusercontent.com/5439644/201580184-96f2b202-ab69-4538-923d-9d6627f3a3da.png)
