### ISSUE TITLE
Add functional save button to project

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#157]
As a user, I may want to be able to save my generated image, so that I can see it or use it again without needing to access the app and reupload the file.

## Definition of Done
- [x] Save button exists on page
- [x] Clicking the save button will save the current canvas image to the user's computer

## Tasks
- [x] Add a save button to the webpage
- [x] Implement JavaScript functions to save a canvas state as a jpg to an end-users machine.
