### ISSUE TITLE
Clean up repository files

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#210]
As a developer, I want to only include necessary files in my project, so that I can minimize redundancy, make it more organized and easier for future developers to use, and keep memory costs as low as possible.

## Definition of Done
- [ ] No PHP files remain in project
- [ ] No Node.js files remain in project
- [ ] No python files remain in project
- [ ] No unused .js, .css, .html files remain in project
- [ ] No unused assets remain in project
- [ ] No empty/unnecessary folders remain in project other than docs folder
- [ ] No placeholder files remain in project

## Tasks
- [ ] Task 1
- [ ] Task 2
