### ISSUE TITLE
Update results parser security and data storage items

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#212]
As a developer, I want to ensure that the results parser is only reading data that it can parse properly and is also storing the maximum and minimum pressure values from the results files, so that I can use those values in both the heat map key and knee visualization and know that my parsed data is accurate.

## Definition of Done
- [x] Maximum and minimum values from results files are stored
- [x] All values from the time that the maximum value occurs are stored and usable for heat map
- [x] Results parser only accepts .csv files for parsing

## Tasks
- [x] #232 
- [x] #260
