### ISSUE TITLE
Enhance UX design and UI elements

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#215]
As a user, I want to feel that an application looks finished and well made, so that I can have more confidence in its results and a better user experience.

## Definition of Done
- [x] SDP Sticker is a pop up
- [x] Dials do not turn too quickly or endlessly
- [x] Buttons and text are styled
- [x] The longer a +/- button is held, the faster it increases or decreases
- [x] App visuals appear more polished
- [x] Resizing objects is smoother and objects remain in their containers

## Tasks
- [x] #238
- [x] #239
- [x] #240
- [x] #241
- [x] #242
- [x] #243
- [x] #244
- [x] #245
- [x] #246
- [x] #247
- [x] #257
- [x] #275

## Stretch Goal Tasks
- Add a 'Reset' button for clearing canvas instead of refreshing page (check w/ team first)
- Refine dial element visual appearance

**Comment by katerosenthal** [comment]
This story took me about 10.75 hours, a lot of which was troubleshooting related to the dial functionality:

- 1 hour on fixing our SDP sticker without using jquery
- 1 hour on disabling the dial turning if it's at its maximum or minimum value
- 3 hours on making the dial turn rate based on its maximum value and 360 degrees
- 40 minutes on styling every button on the page
- 1 hour on making sure all of the text on the page, including inside default buttons, was styled
- 1 hour on increasing the rate of the plus and minus buttons when held down
- 20 minutes on ensure the 'Save' button stays below the canvas
- 1.5 hours on shadow boxes because they initially broke the dials
- 20 minutes on finding and adding a background image
- 15 minutes on fixing a bug that was created by following linter requirements
- 40 minutes on moving, styling, and labeling the 'Zoom' plus and minus buttons
