### ISSUE TITLE
Allow canvas view to zoom in and out

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#217]
As a user, I want to be able to change my field of view on the knee drawing, so that I can focus on specific areas more closely or view the entire knee.

## Definition of Done
- [x] Canvas can zoom in and out
- [x] Images remain accurately drawn when zooming in or out

## Tasks
- [x] Add scroll to zoom in/out functionality to canvas
