### ISSUE TITLE
Update geometry parser to account for bone and cartilage .inp files

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#218]
As a developer, I want to be able to recognize and properly parse both bone and cartilage files, so that the app can handle all .inp files.

## Definition of Done
- [x] Parser recognizes and can differentiate bone and cartilage files
- [x] Parser creates properly sized element arrays based on which type of .inp file is being parsed
- [x] Parser either accounts for or properly ignores 'side nodes' in cartilage files - need to ask sponsor which

## Tasks
- [x] #219
- [x] #234
- [x] #235
- [x] #236
- [x] #249
- [x] #248

**Comment by katerosenthal** [comment]
All of this story that affects the app's functionality is complete. I will continue to work on clean documentation throughout the week, but consider this story complete for its essentials.

**Comment by katerosenthal** [comment]
In total, this story took me 2.6 hours to complete:

- 60 minutes on determining the tissue type of the file
- 20 minutes on making sure the parser only creates 3-node element arrays for bone files
- 40 minutes on making sure that the parser creates 8-node element arrays for cartilage files
- 35 minutes on making sure that the parser ignores the 'side node' section of cartilage files

I would also say that I've spent another 45 minutes - 1 hr going through and documenting code, but am still working on that.
