### ISSUE TITLE
Upload a file to the main page

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#28]
As a user, I want to be able to upload a file to the page, so that I can interact with it through the application.

## Definition of Done
- [ ] A user can successfully upload a file to the webpage
- [ ] An error message is displayed if the upload is not successful

## Tasks
- [ ] Created a functioning upload form

**Comment by shuai-yang** [comment]
The feature of "displaying error message" is moved to the testing task
