### ISSUE TITLE
Parse geometry data files

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#30]
As a developer, I want to be able to parse .inp files, so that I can use the information from them in my application.

## Definition of Done
- [x] Geometry data is broken down into nodes with x, y, z coordinates and elements with nodes.
- [x] Data is temporarily stored in a way useful to the application

## Tasks
- [x] Research and review parsing text files in HTML and JS
- [x] Research and review Node.js for parsing and manipulating files
- [x] #131
- [x] #132
- [x] #133

**Comment by katerosenthal** [comment]
This story took around 11 hours to complete:

- 3 hours of research
- 5 hours of working on parsing
- 3 hours of working on storing the data properly

Because this story was a huge priority for the app's functionality and was already 2 sprints behind when I was assigned to it, completing it was my main priority this sprint over my other story (dial functionality).
