### ISSUE TITLE
Set up CI for project

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#32]
As a developer, I want to have CI running on my project, so that I can automate and streamline integrating code changes throughout my project.

## Definition of Done
- [x] CI is set up and working according to assignment guidelines

## Tasks
- [x] Research and decide on a CI technology to use.
- [x] Setup the CI workflow on the repository.
