### ISSUE TITLE
Create layout on home page

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#33]
As a user, I want to see an intuitive page layout, so that I can easily use and navigate the application.

## Definition of Done
- [x] Home page is created and has a clear layout
- [x] Layout contains a file upload button, a space for a large image/grid, and enough space to add potential dials for parameters

## Tasks
- [x] Create layout/UI mockup and get team approval
- [x] Find an accessible color palette and get team approval
- [x] #54
- [x] #55
- [x] #56
- [x] #57
- [x] #58
