### ISSUE TITLE
Test CI

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#34]
As a developer, I want to ensure that my CI is working properly, so that I can be confident that broken or buggy code isn't being pushed to the main branch of our repository.

## Definition of Done
- [x] Tests written or method well documented
- [x] Test results are consistent and scalable

## Tasks
- [x] Ensure current version of CI is doing what's expected (Generating and comparing linted files with actual content).
- [x] Do some research to make sure the commands are understood and well-documented.

**Comment by BSU-EzekielHolmes** [comment]
I believe according to our definitions of done for this story, everything required has been taken care of.
