### ISSUE TITLE
Research how to create a grid

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#35]
As a developer, I want to create a grid within my application, so that I can display data on precise points within the grid.

## Definition of Done
- [x] An understanding of creating a grid within a web page is shown through comments made on this story or related tasks
- [x] A list of resources/sites used is provided

## Tasks
- [x] Check if we need to import anything to create a grid
- [x] Figure out tools used to create a grid
- [x] Find examples that the team can use in future as reference
- [x] Look into HTML Canvas for future use
- [x] Create plan to follow when doing my first implementation of a grid
