### ISSUE TITLE
Complete and edit final version of team Project Plan

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#36]
As a team member, I want to have a detailed and complete project plan, so that I can present it to my sponsor and receive their approval.

## Definition of Done
- [x] All sections of Project Plan complete
- [x] Project plan is well edited - no typos, cohesive formatting, professional appearance
- [x] All Project Plan rubric requirements are met

## Tasks
- [x] Consult with team and take down collaborative answers and thoughts for each section
- [x] Formally write up all sections of Project Plan with special attention to draft feedback
- [x] Create image for architectural diagram
- [x] Carefully edit, format and proofread Project Plan
- [x] Recieve team's approval for final version of Project Plan before submission
