### ISSUE TITLE
Preliminary code for grid

### ISSUE THREAD

**Issue by katerosenthal** [cs481-ekh/f22-kneed-for-speed#37]
As a developer, I want to begin building a grid, so that I can have an understanding of its complexity for future sprints or have a good base for creating the grid going forward.

## Definition of Done
- [x] Any code submitted or insights on difficulties or issues found left as comments

## Tasks
- [x] Implement HTML Canvas to page layout
- [x] Create an element (square) on the canvas #63 
- [x] Create an element (circle) on the canvas #64 
- [x] Create an element (triangle) on the canvas #65 
- [x] Start looking at dynamically creating these elements. (once team decides on shape we're going to use)

**Comment by mariotorres1** [comment]
Group decided on square elements
