### ISSUE TITLE
Database connected to website

### ISSUE THREAD

**Issue by mitchcrocker** [cs481-ekh/f22-kneed-for-speed#6]
As a team member, I want to have my database connected, so that I can insert and pull data from it.

## Definition of Done
- [ ] PHP code on website successfully connects to database

## Tasks
- [x] Research how to access databases using PHP
- [x] Create a PHP file that connects to a database
