### ISSUE TITLE
Plan and Organize Repo Structure

### ISSUE THREAD

**Issue by mitchcrocker** [cs481-ekh/f22-kneed-for-speed#7]
As a team member, I want to have an organized repository, so that I can develop more efficiently

## Definition of Done
- [ ] Repository is organized
- [ ] Research done for continuous integration

## Tasks
- [x] propose a repo structure
- [x] outline research and findings of CI, possible steps to act on
