### ISSUE TITLE
Initial Page Layout Research

### ISSUE THREAD

**Issue by mitchcrocker** [cs481-ekh/f22-kneed-for-speed#8]
As a sponsor, I want to be able to visualize what the web page will look like, so that I can understand what the end project will look like

## Definition of Done
- [x] Idea of what the web page will look like

## Tasks
- [x] Research if we want to use frameworks or do everything from scratch
- [x] Outline what the web page will look at the start and what it could look like at the end of the project
- [x] Ready to show / discuss with team different ideas
