### ISSUE TITLE
Add Dial Functionality to the UI

### ISSUE THREAD

**Issue by BSU-EzekielHolmes** [cs481-ekh/f22-kneed-for-speed#80]
As a developer, I want to add functionality to my UI dials, so end-users can modify data inputs dynamically.

## Definition of Done
- [x] Dials are no longer static images
- [x] Dials react to user clicking and dragging them
- [x] Dials influence the number displayed below them as they are turned

## Tasks
- [x] Research how to make a dial using CSS and JS
- [x] #128
- [x] #129
- [x] #130

**Comment by katerosenthal** [comment]
After looking into creating dials using only CSS and Javascript, I believe I will need to push this story into the next sprint. I'm still learning javascript, and this story will be very javascript-intensive and much more complex than anything I've created so far.

The best existing examples I could find similar to what we need are volume knobs for music apps. I think a very pared-down version of one of these that is also edited to allow for negative values may work well.  

I want to try to combine ideas and techniques from these three sources in order to make what we need for our project:

https://codepen.io/kevin-lam-the-scripter/pen/QWNeNvo
https://github.com/denilsonsa/html5-knob
https://www.youtube.com/watch?v=C2m4wMfjllA&t=1s

**Comment by katerosenthal** [comment]
Creating the dial elements themselves and making sure they were responsive took me way longer than expected- around 3 hours working just with CSS.

I also chose to prioritize my other story (parsing the .inp files) because it was much more important for the app's functionality at this point. We are not ready to use the dials yet because we were behind on multiple data-handling stories.

Should be in a good place to complete this task early next sprint.

**Comment by katerosenthal** [comment]
Completing this story took me 7 hours total:

- 3 hours on creating the dial elements
- 3.5 hours making the dials interactive
- .5 hours connecting the dial user input to their numeric displays
