### ISSUE TITLE
Add Button Functionality to the UI

### ISSUE THREAD

**Issue by BSU-EzekielHolmes** [cs481-ekh/f22-kneed-for-speed#85]
As a user, I want to be able to click the buttons available in the UI and have them visually affect my input, so I can see that they are working as I expect.

## Definition of Done
- [x] + and - buttons change the number displayed in the corresponding numeric input 

## Tasks
- [x] #103
- [x] Ensure buttons visually change the number displayed to the user
- [x] Enforce a minimum and maximum number
- [x] #104

**Comment by katerosenthal** [comment]
Tasks 2 and 3 ended up being taken care of while implementing task 1

**Comment by katerosenthal** [comment]
Blocked on submitting code for issue 104 until PR for issue 103 is merged.
