### ISSUE TITLE
Responsive Images and Layout

### ISSUE THREAD

**Issue by BSU-EzekielHolmes** [cs481-ekh/f22-kneed-for-speed#87]
As a user, I want to be able to resize the window and still have the application function and look nice, so that I can have the same experience on different screen sizes.

## Definition of Done
- [x] Layout resizes properly when window size changes
- [x] Any images resize properly when window size changes
- [x] Code for layout is understandable and easy to manipulate

## Tasks
- [x]  Research flexbox vs grid
- [x] #88
- [x] #89
- [x] #97
