### ISSUE TITLE
Research Docker and Create Container

### ISSUE THREAD

**Issue by mitchcrocker** [cs481-ekh/f22-kneed-for-speed#9]
As a team member, I want to have a docker file, so that I can build my project easily and efficiently

instructions at sdp.boisestate.edu/students.html

## Definition of Done
- [x] There's a docker image that can build the project
- [x] Email Dr. Henderson that our website is ready to be hosted

## Tasks
- [x] Figure out how to build a docker container using pre-built images.
- [x] Create a Docker container that successfully runs our page.
- [x] Decide on what needs to be submitted to Dr. Henderson to allow the container to host our page on the sdp server.
